User.destroy_all
AllGame.destroy_all
YourGame.destroy_all

victor = User.find_or_create_by(username: "vchoe")

csgo = AllGame.find_or_create_by(title:"Counter-Strike:Global Offensive", front_cover:"https://www.skidrowcrack.com/download/2012/07/639766_224065_front.jpg", back_cover:"https://steamcdn-a.akamaihd.net/steam/apps/730/header.jpg?t=1566587391", rating: 3, screenshot:"https://steamuserimages-a.akamaihd.net/ugc/90469956947714715/291DA03A9D6B67283EE4AC33CF4E8EF8526DF369/", video_url:"https://www.youtube.com/watch?v=ODlmDbtZy8c", description:"Counter-Strike: Global Offensive (CS:GO) expands upon the team-based first person shooter gameplay the original Counter-Strike pioneered when it launched in 1999. Two teams compete in multiple rounds of objective-based game modes with the goal of winning enough rounds to win the match.", system:"PC")

nba2k = AllGame.find_or_create_by(title:"NBA2K20", front_cover:"https://thumbor.forbes.com/thumbor/960x0/https%3A%2F%2Fblogs-images.forbes.com%2Fbrianmazique%2Ffiles%2F2019%2F07%2FUntitled-design-1-1200x675.jpg", back_cover:"https://i.redd.it/gx3g4slzwqi31.jpg", rating: 3, screenshot:"https://i.ytimg.com/vi/tMJr20ptKDk/maxresdefault.jpg", video_url:"https://www.youtube.com/watch?v=UB8L_pvzbIk", description:"Take your skills to the next level with the most realistic player control ever, featuring an upgraded motion engine with signature styles, advanced shooting controls, a new dribble size-up system, refined off-ball collisions, and a new read & react defensive game.", system:"PS4")

death_stranding = AllGame.find_or_create_by(title:"Death Stranding", front_cover:"https://blog.us.playstation.com/tachyon/2019/07/Death-Stranding-featured.jpg?resize=1088,612", back_cover:"https://i.redd.it/ryts0esxntd01.jpg", rating: 4, screenshot:"http://images.pushsquare.com/48e034411adbf/death-stranding-ps4-playstation-4-screenshots-7.original.jpg", video_url:"https://www.youtube.com/watch?v=piIgkJWDuQg", description:"Death Stranding is a completely new type of action game, where the goal of the player is to reconnect isolated cities and a fragmented society. ... As Sam Porter Bridges, you will attempt to bridge the divides in society, and in doing create new bonds or strands with other players around the globe.", system:"PS4")

fortnite = AllGame.find_or_create_by(title:"Fortnite", front_cover:"https://www.mobygames.com/images/covers/l/498744-fortnite-battle-royale-nintendo-switch-front-cover.jpg", back_cover:"https://cdn.shopify.com/s/files/1/0730/3461/products/Fortnite_Xbox_One_2_back_pegi_RR757JPA32TU.jpg?v=1526695810", rating: 3, screenshot:"https://i.redd.it/4dpmqog7zrk01.jpg", video_url:"https://cdn.shopify.com/s/files/1/0730/3461/products/Fortnite_Xbox_One_2_back_pegi_RR757JPA32TU.jpg?v=1526695810", description:"Fortnite is a survival game where 100 players fight against each other in player versus player combat to be the last one standing. It is a fast-paced, action-packed game, not unlike The Hunger Games, where strategic thinking is a must in order to survive.", system:"PC")

apex = AllGame.find_or_create_by(title:"APEX Legends", front_cover:"https://www.mobygames.com/images/covers/l/538006-apex-legends-xbox-one-front-cover.jpg", back_cover:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbYbtT7nxG9r-DA4dRwl3VFIId_3SrSTCu1efZKvw_C8yNPqh5", rating: 3, screenshot:"https://giantbomb1.cbsistatic.com/uploads/original/40/402691/3083075-apex%20legends_20190222211624.jpg", video_url:"https://www.youtube.com/watch?v=UMJb_mkqynU", description: "Apex Legends is a battle royale game in which up to 20 three-man squads land on an island before searching for weapons and supplies to then attempt to defeat all other players in combat.", system:"PC")

mgs4 = AllGame.find_or_create_by(title:"Metal Gear Solid 4:Guns of the Patriots", front_cover:"https://www.mobygames.com/images/covers/l/115412-metal-gear-solid-4-guns-of-the-patriots-playstation-3-front-cover.jpg", back_cover:"https://www.mobygames.com/images/covers/l/115413-metal-gear-solid-4-guns-of-the-patriots-playstation-3-back-cover.jpg", rating:5, screenshot:"https://psmedia.playstation.com/is/image/psmedia/metalgearsolid4_sc009?$TwoColumn_Legacy$", video_url:"https://youtu.be/hCgCjPYi27Q?t=30", description:"Metal Gear Solid 4: Guns of the Patriots[a] is an action-adventure stealth video game developed by Kojima Productions and published by Konami exclusively for the PlayStation 3 console. It is the sixth Metal Gear game directed by Hideo Kojima and was released worldwide on June 12, 2008.", system:"PS4")

aerofight = AllGame.find_or_create_by(title:"Aero Fighters", front_cover:"https://i.ytimg.com/vi/yITvKTIb8QY/hqdefault.jpg", back_cover:"https://gamefaqs1.cbsistatic.com/box/4/9/9/50499_back.jpg", rating:4, screenshot:"https://gamefaqs1.cbsistatic.com/screens/2/b/5/gfs_29341_2_7_mid.jpg", video_url:"https://youtu.be/5Phj-735p30?t=83", description:"Aero Fighters, known as Sonic Wings (ソニックウィングス Sonikku~uingusu) in Japan, is a vertical-scrolling shoot 'em up arcade game originally released in 1992 by Video System and ported to the Super Nintendo Entertainment System in 1993. It was the first in the Aero Fighters series, and a spiritual successor to the 1991 Turbo Force.", system:"SNES")

grand2 = AllGame.find_or_create_by(title:"Grandia II", front_cover:"https://www.mobygames.com/images/covers/l/35178-grandia-ii-dreamcast-front-cover.jpg", back_cover:"https://www.mobygames.com/images/covers/l/35179-grandia-ii-dreamcast-back-cover.jpg", rating:5, screenshot:"https://www.justpushstart.com/wp-content/uploads/2018/08/Grandia-I-II-HD-Remaster-for-Switch.jpg", video_url:"https://youtu.be/BFXmJ1Oyl0I?t=111", description:"Grandia II[a] is a role-playing video game developed by Game Arts originally for the Dreamcast console as part of their Grandia series. Initially released in Japan in August 2000 by Game Arts, the game was later made available in English for North America the following December, and in Europe in February 2001, with both releases published by Ubi Soft. The game was later ported to the Sony PlayStation 2, where it was released worldwide throughout 2002, and later for Microsoft Windows exclusively in North America and Europe later that year. An enhanced port, based upon the Dreamcast version and entitled Grandia II Anniversary Edition was released on August 24, 2015 on Steam and GOG.com. A high-definition remaster of the game will be released in North America and Europe on August 16, 2019, together with one of the original, for Nintendo Switch; an associated update for the Windows PC Anniversary Edition will follow later in 2019.[3][4] GungHo Online Entertainment clarified that a Japanese release of the remasters will follow in the future.[5]", system:"Dreamcast")

sotc = AllGame.find_or_create_by(title:"Shadow of the Colossus", front_cover:"https://images-na.ssl-images-amazon.com/images/I/51NswfdT5dL.AC_SX430_.jpg", back_cover:"https://i.neoseeker.com/boxshots/R2FtZXMvUGxheXN0YXRpb25fMi9BZHZlbnR1cmUvRmFudGFzeQ==/shadow_of_the_colossus_backcover_large_2JcmfQnPFj1jcVz.jpg", rating:4, screenshot:"https://i.imgur.com/Bfcqq4I.jpg", video_url:"https://youtu.be/nsO0SCp1WSk?t=1145", description:"Shadow of the Colossus, released in Japan as Wander and the Colossus,[a] is an action-adventure game developed by SCE Japan Studio and Team Ico, and published by Sony Computer Entertainment for the PlayStation 2. The game was released in North America and Japan in October 2005 and PAL regions in February 2006.[1] It was directed by Fumito Ueda and developed at SCEI's International Production Studio 1, also known as Team Ico; the same development team responsible for the cult hit Ico,[2][3] to which the game is considered a spiritual successor.", system:"PS2")

ff7 = AllGame.find_or_create_by(title:"Final Fantasy 7", front_cover:"https://m.media-amazon.com/images/I/51tkmb93AiL._SR500,500_.jpg", back_cover:"https://gamefaqs1.cbsistatic.com/box/7/8/3/783_back.jpg", rating:4, screenshot:"https://i.kinja-img.com/gawker-media/image/upload/s--2_Bhl679--/c_scale,f_auto,fl_progressive,q_80,w_800/miiesmsfj2bzg7ppza9x.png", video_url:"https://youtu.be/KhSicdniIng?t=949", description:"Final Fantasy VII[a] is a 1997 role-playing video game developed by Square for the PlayStation console. It is the seventh main installment in the Final Fantasy series. Published in Japan by Square, it was released in other regions by Sony Computer Entertainment and became the first in the main series to see a PAL release. The game's story follows Cloud Strife, a mercenary who joins an eco-terrorist organization to stop a world-controlling megacorporation from using the planet's life essence as an energy source. Events send Cloud and his allies in pursuit of Sephiroth, a superhuman intent on destroying their planet. During the journey, Cloud builds close friendships with his party members, including Aerith Gainsborough, who holds the secret to saving their world.", system:"PS1")

game1 = YourGame.find_or_create_by!(user_id: victor.id, game_id: grand2.id, title:"Grandia II", front_cover:"https://www.mobygames.com/images/covers/l/35178-grandia-ii-dreamcast-front-cover.jpg", back_cover:"https://www.mobygames.com/images/covers/l/35179-grandia-ii-dreamcast-back-cover.jpg", rating:5, screenshot:"https://www.justpushstart.com/wp-content/uploads/2018/08/Grandia-I-II-HD-Remaster-for-Switch.jpg", video_url:"https://youtu.be/BFXmJ1Oyl0I?t=111", description:"Grandia II[a] is a role-playing video game developed by Game Arts originally for the Dreamcast console as part of their Grandia series. Initially released in Japan in August 2000 by Game Arts, the game was later made available in English for North America the following December, and in Europe in February 2001, with both releases published by Ubi Soft. The game was later ported to the Sony PlayStation 2, where it was released worldwide throughout 2002, and later for Microsoft Windows exclusively in North America and Europe later that year. An enhanced port, based upon the Dreamcast version and entitled Grandia II Anniversary Edition was released on August 24, 2015 on Steam and GOG.com. A high-definition remaster of the game will be released in North America and Europe on August 16, 2019, together with one of the original, for Nintendo Switch; an associated update for the Windows PC Anniversary Edition will follow later in 2019.[3][4] GungHo Online Entertainment clarified that a Japanese release of the remasters will follow in the future.[5]", system:"Dreamcast")
